#!/usr/bin/env python
import logging
from virtualpad.server import VirtualPadService


# The logger goes here.
logging.basicConfig()
LOGGER = logging.getLogger("virtualpad")
LOGGER.setLevel(logging.INFO)


if __name__ == "__main__":
    try:
        LOGGER.info("Initializing service")
        VirtualPadService(device_name="Hawa-Virtualpad").main()
    except Exception as e:
        LOGGER.exception("An error occurred!")
    finally:
        LOGGER.info("Terminating service")
