#!/usr/bin/env python
import logging
from virtualpad.server import main
from virtualpad.admin import using_admin_channel


# The logger goes here.
logging.basicConfig()
LOGGER = logging.getLogger("virtualpad")
LOGGER.setLevel(logging.INFO)


if __name__ == "__main__":
    try:
        LOGGER.info("Initializing service")
        with using_admin_channel() as (messages, admin_reader):
            main(messages, admin_reader, "Hawa-Virtualpad")
    except Exception as e:
        LOGGER.exception("An error occurred!")
    finally:
        LOGGER.info("Terminating service")
