#!/usr/bin/env python
import logging
from virtualpad.server import VirtualPadService


"""
Ensure this file has permissions 0o500 (only user, only read-execute).
Also ensure that this file is run in the context of a boot service.
"""


# The logger goes here.
logging.basicConfig()
LOGGER = logging.getLogger("virtualpad-server")
LOGGER.setLevel(logging.INFO)


if __name__ == "__main__":
    try:
        LOGGER.info("Initializing service")
        VirtualPadService(device_name="Hawa-Virtualpad").main()
    except Exception as e:
        LOGGER.exception("An error occurred!")
    finally:
        LOGGER.info("Terminating service")
