#!/usr/bin/env python
import os
import logging


logging.basicConfig()
LOGGER = logging.getLogger("admin-send")
LOGGER.setLevel(logging.INFO)
START_USER = os.getenv('FOR_USER') or os.getenv('USER')
_FIFO_PATH = f"/home/{START_USER}/.config/Hawa/run"
_FIFO_SERVER_TO_ADMIN = f"{_FIFO_PATH}/server-to-admin"


def main():
    LOGGER.info("Starting receiver loop")
    with open(_FIFO_SERVER_TO_ADMIN, 'r') as f:
        while True:
            line = f.readline().strip()
            if line:
                LOGGER.info(f">>> Received: {line}")


if __name__ == "__main__":
    main()
